Dirichlet multinomial
NIWAFisheriesModelling/CASAL2 pull request #405
Opened 2022-09-06 23:03 UTC by NIWAFisheriesModelling

* **Please check that the PR fulfills these requirements**

- [x] The commit message follows the Contributor Guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documents have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

The Dirichlet multinomial likelihood, referencing Thorson et al. (2017) Fisheries Research.

* **What is the current behavior?** (You can also link to an open issue here)

This feature does not exist.

* **What is the new behavior (if this is a feature change)?**

Craig Marsh has added the Dirichlet multinomial likelihood.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No.

* **Other information**:

Issue #401

2022-09-07 06:43 UTC, NIWAFisheriesModelling commented
Added a TestModel "LIM_tc_Dm" to show how to configure the theta parameter (as log_theta).

Stock Synthesis 3 estimates log_theta instead of theta. Search "dirichlet_Parm" in [SS_objfunc.tpl](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/d9dd61d86a920dc4940cd61856185235757c31d4/SS_objfunc.tpl) and [SS_write_report.tpl](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/d9dd61d86a920dc4940cd61856185235757c31d4/SS_write_report.tpl).

@Craig44 Please indicate if additional tests are needed.

2022-09-08 00:02 UTC, Craig44 requested changes

2022-09-08 00:48 UTC, Craig44 commented on TestModels/LIN_tc_Dm/estimate_betadiff.log
> +initialisation_phase[1]: 688682
Discussed in https://github.com/NIWAFisheriesModelling/CASAL2/issues/401

2022-09-08 00:48 UTC, Craig44 approved these changes

2022-09-08 05:13 UTC, merged